version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/environment.yml

# python:
#     version: 3.7
#     install:
#       - method: pip
#         path: ./python/ipywidgets
#       - requirements: docs/requirements.txt
